### ISSUE TITLE
T & C checkbox on profiles?

### ISSUE THREAD

**Issue by robbrandt** [veda-consulting-company/uk.co.vedaconsulting.gdpr#126]
We gather data from our members, but often not in relation to an Event or Contribution.  GDPR has nothing to do with collecting money.  Is it possible to add a GDPR Terms & Conditions checkbox to any profile?

**Comment by robbrandt** [comment]
Same question for Communications preferences.  Can I include these on a profile?

**Comment by pk825** [comment]
I have the same questions: how is it possible to add the comunication preferences on a profile in order to sign up to a mailing list. I try to redirect to the preferences pages, but it doesn't work for an anonymous user.

**Comment by tapashdatta** [comment]
A new checkbox "Use as the mailing subscribe page" is included in recent release.

**Comment by masetto** [comment]
The original question of @robbrandt was:
> Is it possible to add a GDPR Terms & Conditions checkbox to any profile?

@tapashdatta, the checkbox "Use as the mailing subscribe page" add Communication preferences but does not add Terms & Conditions checkbox which is used instead in contribution and event pages.

How can I add "Terms & Condition" in a profile? (for example "Become a volunteer", signup form...)
