### ISSUE TITLE
Subscription to Groups at Event/Contribution sign-up

### ISSUE THREAD

**Issue by edlifecycle** [veda-consulting-company/uk.co.vedaconsulting.gdpr#128]
The GDPR extension allows "Terms" & "Privacy Policy" tickboxes to appear universally at the bottom of Event or Contribution pages - which is great.  

However, there is no ability to make opt-in tickboxes for **Groups** appear on Event or Contribution pages - so new customers can sign-up to a Newsletter whilst booking.

This functionality does exist within the extension: in the "Subscriptions to Groups" section of the GDPR dashboard Communication Settings - displayed as tickboxes on the public Communication Preferences page.  Is it possible to enable this "Subscription to Groups" tickbox menu to appear universally above the "Terms" & "Privacy Policy" tickboxes on:

- Event registrations
- Contribution pages 
- Webforms

There will be a lot of organisations who will want to allow Newsletter sign-up during the booking process (at any entry point), so this would be a massively useful upgrade. 

Thanks.

**Comment by veda-consulting** [comment]
@edlifecycle our plans for this are to allow the extension to automatically add links to the comms prefs pages on the thank you page of registrations/contributions. This is in order to not overload the pages with a bunch of comms prefs options. How does that sound?

**Comment by edlifecycle** [comment]
The reality is, if it requires an extra clickthrough at the end of a booking, most people simply won't bother. Especially if the link is buried in the Thank You page: example pic attached 

The majority of CiviCRM users are mission-led organisations, for whom supporter and Newsletter sign-up is vital.  Sign-up needs to be as simple and clear as possible, via any entry point: otherwise under GDPR our opted-in comms lists will gradually dwindle away and die due to lack of new sign-ups.

![group subscription - buried](https://user-images.githubusercontent.com/39797432/40783261-d64dc160-64d9-11e8-857c-07329ecc8cc7.png)

**Comment by veda-consulting** [comment]
@edlifecycle I understand. Maybe a compromise might be to ask them on the confirmation page? Prior to submission?

**Comment by edlifecycle** [comment]
Talking to other users, we have 2 issues about asking on the confirmation page:

1) Many events don't use confirmation pages
2) For those that do, it's another step that may increase booking drop-off

How about embedding the Group Subscription options as the top item on the Thank You page - as mocked-up below?  It wouldn't clog the booking process and (presumably) existing clients would have their current subscriptions pre-loaded, to review and update? 
 
This is probably the most useful solution for most of the CiviCRM community.

![group subscription - suggested](https://user-images.githubusercontent.com/39797432/40788291-98fa31d2-64e7-11e8-975b-7b6f324f8d00.png)

**Comment by veda-consulting** [comment]
@edlifecycle ok, that sounds doable. I'll get that scheduled in for v2.7.

**Comment by edlifecycle** [comment]
Awesome, thanks!

Final question: will this be available on Webforms too? Currently we can't get Terms / Privacy policy tickboxes onto Webforms, so will this be the same?

**Comment by veda-consulting** [comment]
@edlifecycle we'll have to do webforms as a separate exercise and would probably need some funding to make it happen. Once this issue has been resolved we can have a chat about how best to make it happen.

**Comment by tapashdatta** [comment]
Feature added to recent release.
