### ISSUE TITLE
Delete Activities of Types

### ISSUE THREAD

**Issue by JoeMurray** [veda-consulting-company/uk.co.vedaconsulting.gdpr#141]
There are dozens of Activity Types by Default. Adding additional Activity Types is not uncommon, including after system configuration and GDPR have been setup. I'm not clear why and when it would be appropriate to keep activities on person being forgotten. 

Rather than having a multi-select that generally has to have all options selected and then is likely to be missed instead of updated when a new Activity Type is created, wouldn't it be better to either provide an option to delete all Activity Types, or make the select for the Activity Types to keep?

**Comment by TerryVeda** [comment]
See also issue 163

**Comment by veda-consulting** [comment]
@TerryVeda https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/issues/163 is now closed, is this the same thing? Can we close?

**Comment by tapashdatta** [comment]
Fixed in recent release.
