### ISSUE TITLE
'SLA Acceptance' is not a valid option for field activity_type_id

### ISSUE THREAD

**Issue by hanswundersam** [veda-consulting-company/uk.co.vedaconsulting.gdpr#154]
We receive the above error message whenever we try to open a contact page. The error

`'SLA Acceptance' is not a valid option for field activity_type_id`

only appears when the GDPR extension is activated. Once we disable it, everything's back to normal. The same behaviour had been described in [this closed issue from April](https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/issues/71), but the solution suggested does not work for us (and it's unclear whether it has worked back then).

Is it possible that there's a persisting bug in v2.6? Thank you for looking into it.

GDPR Extension 2.6
CiviCRM 5.3.2
PHP 5.6.37
Wordpress 4.9.7

**Comment by TerryVeda** [comment]
See also issues 96, 134

**Comment by tapashdatta** [comment]
Fixed in recent release.
