### ISSUE TITLE
Save information that data were exported

### ISSUE THREAD

**Issue by scardinius** [veda-consulting-company/uk.co.vedaconsulting.gdpr#157]
Because of GDPR rules we have to save information that some data were exported. Those could be contact, activity or contribution objects.

I'm going to prepare solution for action "Export contacts", "Export actiivities" etc.
Each exported object will have a new type activity, for example "Contact exported", "Activity exported" with additional fields as id of object, subject, who exported.

It's necessary to use new type of hook, because hook_civicrm_export doesn't have ids of objects
https://github.com/scardinius/civicrm-core/commit/f46c37304de63001b7da3f62ac15d12eb32d6446

So at this branch caltha-eu:dev-157 is my proposal
https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/compare/master...caltha-eu:dev-157?expand=1

**Comment by veda-consulting** [comment]
Hi @scardinius 
Do you feel these changes are production ready? We are due to release a new version of the GDPR extension in the next week and would like to include this functionality if possible?

**Comment by scardinius** [comment]
Hi @veda-consulting 
this feature needs more testing from our side although it looks quite good.

Apart from that it relies on new civicrm hook https://github.com/scardinius/civicrm-core/commit/f46c37304de63001b7da3f62ac15d12eb32d6446 which is not included into civicrm core yet. I think we should wait until CRM_Utils_Hook::exportIds will be official hook.

**Comment by scardinius** [comment]
Hi @veda-consulting I've just published my proposal for new type of hook needed for this feature
https://lab.civicrm.org/dev/core/issues/457

**Comment by scardinius** [comment]
Hi @veda-consulting I have a good news :-) Core team approved my modifications to export hook
https://lab.civicrm.org/dev/core/issues/457 and they will be available from CiviCRM 5.8

PR #176 is ready to use

**Comment by scardinius** [comment]
Hi @veda-consulting I created a fix for this feature because civicrm core changed a bit :-)

**Comment by tapashdatta** [comment]
Fixed in recent release.
