### ISSUE TITLE
Data Policy tab incorrect

### ISSUE THREAD

**Issue by Czollli** [veda-consulting-company/uk.co.vedaconsulting.gdpr#173]
Hi,
Wordpress 4.9.8
gdpr extension 2.6

on gdpr settings page the url looks:
https://example.uk/**wp-admin**/wp-content/plugins/files/civicrm/persist/contribute/Privacy%20Policy.pdf
on an event page
https://example.uk/**civicrm**/wp-content/plugins/files/civicrm/persist/contribute/Privacy%20Policy.pdf

which in both cases give 404.
Without the highlighted bits pdf loading fine.

Could you have a look?
Thanks

**Comment by veda-consulting** [comment]
Hi @Czollli is this still an issue?
