### ISSUE TITLE
Data Policy Introductory text does not appear when using the contribution page's Terms & Conditions instead of defaults

### ISSUE THREAD

**Issue by freeform-sg** [veda-consulting-company/uk.co.vedaconsulting.gdpr#177]
Thanks for all of your hard work on this extension!

When configuring Terms & Conditions for a specific contribution page, the Terms & Conditions tab does not provide a field for overriding the Introduction text, nor does the default text display, so if you want Introduction text you have to enable Terms & Conditions for all contributions pages. Would it be possible to include an Introduction text field on the Terms & Conditions contribution/event tab? Either that or always display the default text if there's a reason it needs to be consistent.

The wrapper div for the intro is being output, but its contents are empty.

`<div class="content">`
`<div class="terms-conditions-acceptance-intro">`
`</div>`

**Comment by tapashdatta** [comment]
Fixed in recent release.
