### ISSUE TITLE
How to require Data Policy acceptance on a contribution or event without also requiring acceptance of T & C?

### ISSUE THREAD

**Issue by freeform-sg** [veda-consulting-company/uk.co.vedaconsulting.gdpr#178]
This is in reference to comments on #155 - the original issuer complained of an issue of preferences not saving in WP, as well as "Question no. 1: Is it possible to only show the Data Policy OR the Terms & Conditions, but not both?". These two things are unrelated and should be treated as separate issues.

We are looking to display the Data Policy but not the Terms & Conditions (because why would you need acceptance of both? Would a well-written Data Policy not cover all of the items that require consent?) Having to accept multiple boxes may deter potential contributors.

Alternatively (or in addition to), we'd like to decide if acceptance of the Terms & Conditions is visible but optional, while the Data Policy acceptance remains required. We'd like non-agreement to not prevent the user from completing a contribution, but limit their access to the system as a result.

The later can be achieved with a custom field outside of GDPR, but it would be nicer/more convenient to make use of the T&C field. We certainly don't want 3 checkboxes, so if using the T&C field for this purpose isn't possible, we need to be able to disable T&C while maintaining the Data Policy check.

**Comment by freeform-sg** [comment]
I'd like to add, also, that I don't think the original question, "Question no. 1: Is it possible to only show the Data Policy OR the Terms & Conditions, but not both?" is the way to go, IMO the Data Policy should always be required and present.

**Comment by tapashdatta** [comment]
PR welcome.
