### ISSUE TITLE
Feature request: support for multilingual sites

### ISSUE THREAD

**Issue by freeform-sg** [veda-consulting-company/uk.co.vedaconsulting.gdpr#179]
The extension current only supports a single language. _We are currently checking to see if it would be within out client's budget to contribute to the addition of this feature, which we may be able to help with the development of._

Can you highlight any caveats in the current logic that may make this difficult to implement?

Thanks!

**Comment by deepak-srivastava** [comment]
I've tried setting up multilingual site with drupal & wordpress (latest) with Civi 5.8.2 and gdpr 2.7 - and it seems to work fine w.r.t functionality (not breaking anything). 

When you say 'does not support' - do you mean mainly translations or see problems with functionality?

**Comment by freeform-sg** [comment]
Unless I am missing something, the extension assumes the contacts will only
visit  the site in a single language - the text boxes are not translatable,
and there's untranslated hard-coded text so everyone sees the same text and
pdf files regardless of the language they're using the site in. We are
using JS to translate our fields and other text and have created a single
PDF with both the English and French policy info in it as a workaround, but
that means our client can't change/update any of the translations
themselves, they have to rely on a developer.

**Comment by tapashdatta** [comment]
Assuming fixed in recent release. Please re-open if still is an issue (PR welcome). Thanks
