### ISSUE TITLE
Terms & Conditions title should be a title not a label

### ISSUE THREAD

**Issue by freeform-sg** [veda-consulting-company/uk.co.vedaconsulting.gdpr#180]
When looking at a contribution form, the section title "Terms & Conditions" is output as a label instead of a heading. Section could, perhaps, be output with the same styling as a profile for consistency, with the required asterix printed next to each checkbox label rather than the section title.

Consider replacing:

`<div class="crm-section">`
`<div class="label">`
`<label>Terms &amp; Conditions  <span class="crm-marker" title="This field is required">*</span></label>`
`</div>`
`<div class="content">`
`<div class="terms-conditions-acceptance-intro">`
`</div>`
`</div>`
`</div>`

With:

`<legend>Terms &amp; Conditions</legend>`
`<div class="content">`
`<div class="terms-conditions-acceptance-intro">`
`</div>`
`</div>`

**Comment by tapashdatta** [comment]
Fixed in recent release.
