### ISSUE TITLE
Communication Preferences - Email/Post UI Not Updating

### ISSUE THREAD

**Issue by reecebenson** [veda-consulting-company/uk.co.vedaconsulting.gdpr#181]
### Relates To
This issue relates to the page:
"<url>/civicrm/gdpr/comms-prefs/update"

## Expected Behaviour
- Updating "Email" / "Post" should reflect the values set on the Contact in CiviCRM (either "Yes" or "No")

## Current Behaviour
- The select input boxes for "Email" and "Post" always default to "Yes"

## Steps to Reproduce
I believe this is a User Interface bug on the URL this issue relates to. There are additional screenshots below.
1. Visit "<url>/civicrm/gdpr/comms-prefs/update"
2. Update "Email" and/or "Post" to "No"
3. Save
4. "Email" and "Post" will be set to "No"
5. Refresh this page (just go to the URL bar and click enter, refreshing will resubmit this form/keep the state of the select input boxes)
6. "Email" and "Post" will now be displayed as "Yes", however the Contact in CiviCRM will have:
    - "DO NOT MAIL"
    - "NO BULK EMAILS (USER OPT OUT)"

### Screenshots
1. How it looks when I visit "<url>/civicrm/gdpr/comms-prefs/update":
![image](https://user-images.githubusercontent.com/7308809/49449670-5457cb00-f7d3-11e8-84f4-81b7c4f284d8.png)

2. I then set the preferences all to "No":
![image](https://user-images.githubusercontent.com/7308809/49449694-633e7d80-f7d3-11e8-9320-98c07a211d12.png)

3. Then press Save:
![image](https://user-images.githubusercontent.com/7308809/49449717-6a658b80-f7d3-11e8-8502-ef3e4a9eafb5.png)

4. Then visit "<url>/civicrm/gdpr/comms-prefs/update" again ("Email"/"Post" are shown as 'Yes' but the Contact has them set to 'No')
![image](https://user-images.githubusercontent.com/7308809/49449748-7bae9800-f7d3-11e8-9334-04a6be5d006f.png)

### Additional Information
- I was able to reproduce this on more than two sites.

**Comment by tapashdatta** [comment]
Fixed in recent release.
