### ISSUE TITLE
Feature request: replace hard-coded "Please read and accept the Privacy policy" on Communications Preferences page with a custom intro field like is done for contribution and event pages

### ISSUE THREAD

**Issue by freeform-sg** [veda-consulting-company/uk.co.vedaconsulting.gdpr#182]
Any hard-coded text is much more difficult to translate. Our workaround for our bilingual site is to put English & French text into each of the custom fields, but there are still some straggling hard-coded titles. The intro for the Contribution and Event pages is an example where the same intro is hard-coded for the Communication Preferences page.

**Comment by freeform-sg** [comment]
Also, there's a typo in the mark-up for this section; the classes for the div are "`data-policy-intro section-sescription`", I suspect this was supposed to be "`data-policy-intro section-**d**escription`"

**Comment by tapashdatta** [comment]
Fixed in latest branch.
