### ISSUE TITLE
Unsure why "Source of Communication Preferences" is appearing on Communications Page when accessed via token

### ISSUE THREAD

**Issue by freeform-sg** [veda-consulting-company/uk.co.vedaconsulting.gdpr#184]

**Comment by freeform-sg** [comment]
If you are logged-out and access the communication preferences page using a token in an email, everything looks OK. 

If you are logged-in and access the preferences page without the user hash on the end of the URL, everything looks OK.

If you are logged-in and access the preferences page via a token in an email with the user hash on the end then there is an extra field "_Source of Communication Preferences_" with an empty text field. I am hiding it with css for now.

**Comment by tapashdatta** [comment]
Could not reproduce with the latest branch.
