### ISSUE TITLE
JS error when submitting communication preference at thank you page.

### ISSUE THREAD

**Issue by tapashdatta** [veda-consulting-company/uk.co.vedaconsulting.gdpr#206]
<img width="700" alt="Screenshot 2019-07-12 at 21 46 06" src="https://user-images.githubusercontent.com/5366545/61159064-b9566a80-a4f2-11e9-895c-1abeb680b707.png">

**Comment by pradpnayak** [comment]
@tapashdatta can you try https://github.com/veda-consulting/uk.co.vedaconsulting.gdpr/issues/206 ?
