### ISSUE TITLE
GDPR extension breaks event registration on CiviCRM 5.20

### ISSUE THREAD

**Issue by JGaunt** [veda-consulting-company/uk.co.vedaconsulting.gdpr#211]
Hi all,

We have upgraded a few sites to 5.20 and the GDPR extension doesn't work nicely with it when users try to register for events (both logged in and logged out users).

When anyone attempts to register for an event with the extension installed and enabled, after they fill their details in and click register, they are given a 500 Error.

Having a look at the error logs, we have the following notices:

> Notice: Undefined index: entity_tc_option in CRM_Gdpr_SLA_Entity->addField() (line 168 of /home/site/public_html/sites/salfordcvs.co.uk/civicrm_extensions/uk.co.vedaconsulting.gdpr/CRM/Gdpr/SLA/Entity.php).

> Notice: Undefined index: sla_data_policy_option in CRM_Gdpr_SLA_Utils::getTermsConditionsUrl() (line 195 of /home/site/public_html/sites/salfordcvs.co.uk/civicrm_extensions/uk.co.vedaconsulting.gdpr/CRM/Gdpr/SLA/Utils.php).

Once we disabled the extension, the event registration worked as normal.

Thanks,
Jade

**Comment by tapashdatta** [comment]
Fixed in latest commit, changes committed to master.
