### ISSUE TITLE
'Activity export' 'contact export' activities issue

### ISSUE THREAD

**Issue by Sez0105** [veda-consulting-company/uk.co.vedaconsulting.gdpr#216]
Hello,

I can see a change on the 2.8 version of GDPR that it now creates an activity of 'activity or contact export', depending upon the export type. 
This maybe good for some of our clients who want to track this, but a few have stated they don't want this feature. 
One client has had 28000 activities added due to this change, after they exported activity data for 3 months work. 
Disabling/deleting the activity type doesn't work either, the activity gets re added every time an export happens. 

Is there a way we can use GDPR but stop it from recording these activities? Could a check box be added in the GDPR settings asking if they want to track export's? Currently having to disable on the sites that are reporting this feature isn't required for there policies, exporting is given to trusted roles only. 

Thanks

Sarah

**Comment by veda-consulting** [comment]
@Sez0105 thanks for the feedback, yes I think this is a good idea and I think its also related to another issue #220 We'll take a look at doing this ASAP

**Comment by tapashdatta** [comment]
A configurable setting is included in recent release.
