### ISSUE TITLE
GDPR extension ver. 2.8 issue? (in exporting data, from 5.18.2 to 5.22 CiviCRM ver.)

### ISSUE THREAD

**Issue by alexletizia** [veda-consulting-company/uk.co.vedaconsulting.gdpr#220]
Hi all

We manage CiviCRM for some NPO in SaaS mode. We noticed that probably the GDPR extension ver. 2.8 has some problems.

Indeed on:

- Wordpress 5.3.2

- both on PHP ver. 7.3 and ver. 7.2

- both whit PHP-FPM and Fast-CGI compression

- PHP open_basedir both enabled and disabled

- MySQLversion: 10.3.22-MariaDB-0 + deb10u1

- on all CiviCRM ver. from 5.18.2 to 5.22

a simple export to .csv of only 2000 contacts (only Name, Surname, Email) takes at least 200 seconds and causes the host down (if it is set to the canonical 100s Time Over)

We also have the feeling that everything is going a little slower, especially to access CiviCRM at the first connection

With version 2.7 of the GDPR Extention the same operation closes correctly on 3 seconds.

Thx&Bye

**Comment by veda-consulting** [comment]
@alexletizia we are taking a look

**Comment by alexletizia** [comment]
Thx a lot.

**Comment by veda-consulting** [comment]
@alexletizia we think this might be down to activities being tracked now when contacts are exported. We're looking at turning this into a configurable setting - that will be off by default. See #216

**Comment by tapashdatta** [comment]
A configurable setting is included in recent release.
