### ISSUE TITLE
Update communication preferences from email token gives error

### ISSUE THREAD

**Issue by mikantchap** [veda-consulting-company/uk.co.vedaconsulting.gdpr#231]
Using a token in an email {CommunicationPreferences.comm_pref_supporter_url}
Makes a link like: civicrm/gdpr/comms-prefs/update?reset=1&cid=25107&cs=747373b83b354a72ca6ce05f47103ecf_1592489855_168

Get an error:

CRM_Core_Exception: The requested Profile (gid=139) is disabled OR it is not configured to be used for 'Profile' listings in its Settings OR there is no Profile with that ID OR you do not have permission to access this profile. Please contact the site administrator if you need assistance. in /home/<domainfolder>/public_html/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr/CRM/Gdpr/Form/UpdatePreference.php on line 192

Exception trace
#	Function	Location
0	CRM_Core_BAO_UFGroup::getFields(139, false, 1, null, null, false, null, false, null, 4, 'field_name', true)	/home/<domainfolder>/public_html/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr/CRM/Gdpr/Form/UpdatePreference.php:192
1	CRM_Gdpr_Form_UpdatePreference->buildCustom('139')	/home/<domainfolder>/public_html/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.gdpr/CRM/Gdpr/Form/UpdatePreference.php:73
2	CRM_Gdpr_Form_UpdatePreference->buildQuickForm()	/home/<domainfolder>/public_html/sites/all/modules/civicrm/CRM/Core/Form.php:595
3	CRM_Core_Form->buildForm()	/home/<domainfolder>/public_html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Display.php:76
4	CRM_Core_QuickForm_Action_Display->perform(Object(CRM_Gdpr_Form_UpdatePreference), 'display')	/home/<domainfolder>/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php:203
5	HTML_QuickForm_Controller->handle(Object(CRM_Gdpr_Form_UpdatePreference), 'display')	/home/<domainfolder>/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php:103
6	HTML_QuickForm_Page->handle('display')	/home/<domainfolder>/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php:335
7	CRM_Core_Controller->run()	/home/<domainfolder>/public_html/sites/all/modules/civicrm/CRM/Utils/Wrapper.php:98
8	CRM_Utils_Wrapper->run('CRM_Gdpr_Form_Up…', 'UpdatePreference', Array)	/home/<domainfolder>/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php:284
9	CRM_Core_Invoke::runItem(Array)	/home/<domainfolder>/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php:68
10	CRM_Core_Invoke::_invoke(Array)	/home/<domainfolder>/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php:36
11	CRM_Core_Invoke::invoke(Array)	/home/<domainfolder>/public_html/sites/all/modules/civicrm/drupal/civicrm.module:456
12	civicrm_invoke('gdpr', 'comms-prefs', 'update')	/home/<domainfolder>/public_html/includes/menu.inc:527
13	menu_execute_active_handler()	/home/<domainfolder>/public_html/index.php:21
14	{main}

There is no profile with gid=139. 

I have tried uninstalling the gdpr extension and re-installing it.

**Comment by mikantchap** [comment]
Hi Can anyone help with this issue? Thanks Mike

**Comment by tapashdatta** [comment]
Fixed in latest commit, merged to master.
