### ISSUE TITLE
Unable to 'Forget Me' since set is_deceased to not null in schema  

### ISSUE THREAD

**Issue by BeccaTregenna** [veda-consulting-company/uk.co.vedaconsulting.gdpr#235]
We are unable to use the 'Forget me' since upgrading/patching which I believe is related to:

https://lab.civicrm.org/dev/core/-/issues/1697

When now trying to 'forget' logs show the following error:

[nativecode=1048 ** Column 'is_deceased' cannot be null]

**Comment by tapashdatta** [comment]
Fixed in latest commit, merged to v3.0
