### ISSUE TITLE
Add a search action to bulk "anonymize" contacts

### ISSUE THREAD

**Issue by elcapo** [veda-consulting-company/uk.co.vedaconsulting.gdpr#237]
This issue goes along with a pull request that adds a search action: **anonymize** that facilitates executing the anonymize action for selections of contacts. Only contacts with permission to **forget contact** will see the action and will be able to execute it:

![Screenshot from 2020-09-09 09-33-54](https://user-images.githubusercontent.com/1746692/92575003-bb939080-f27f-11ea-879f-f311dbe48b96.png)

**Comment by tapashdatta** [comment]
PR merged
