### ISSUE TITLE
DB Error: no such field

### ISSUE THREAD

**Issue by robbrandt** [veda-consulting-company/uk.co.vedaconsulting.gdpr#242]
Hi.  We've been using your extension for a while successfully on a couple of sites.  I am creating a new site, basically the same as the others, using the same Drupal 7, CiviCRM and extension versions.  CiviCRM 5.6.1 (we have to upgrade php before going farther). Almost everything is working great.

But with the GDPR extension, when we try to complete a transaction, we get:

CiviCRM_API3_Exception: "DB Error: no such field"

The original extension version we tried is what we'd been using before, labeled 2.7.  However there may have been updates to it based on some other issues we posted here and applied fixes for.  So it may not be an unaltered 2.7. With that version, I have gone so far as to try and completely uninstall the extension and re-install it, thinking a reinstall might create a field that was missing.  No such luck.

Next I tried upgrading to your latest version 2.9.  Still fails the same way. Also tried uninstalling and reinstalling, still no luck.  I am out of ideas.

I would note that when reinstalling for both versions, configuration items were noted as "found", which I think means they weren't removed during uninstall.  Just FYI.

Here's the stack trace:

`CiviCRM_API3_Exception: "DB Error: no such field"

#0 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gdpr/CRM/Gdpr/SLA/Utils.php(153): civicrm_api3("Activity", "create", (Array:6))
#1 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/default/files/civicrm/ext/uk.co.vedaconsulting.gdpr/gdpr.php(332): CRM_Gdpr_SLA_Utils::recordSLAAcceptance("2")
#2 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(274): gdpr_civicrm_postProcess("CRM_Contribute_Form_Contribution_Confirm", Object(CRM_Contribute_Form_Contribution_Confirm))
#3 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(85): CRM_Utils_Hook->runHooks((Array:62), "civicrm_postProcess", 2, "CRM_Contribute_Form_Contribution_Confirm", Object(CRM_Contribute_Form_Contribution_Confirm), NULL, NULL, NULL, NULL)
#4 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(90): CRM_Utils_Hook_DrupalBase->invokeViaUF(2, "CRM_Contribute_Form_Contribution_Confirm", Object(CRM_Contribute_Form_Contribution_Confirm), NULL, NULL, NULL, NULL, "civicrm_postProcess")
#5 [internal function](): Civi\Core\CiviEventDispatcher::delegateToUF(Object(Civi\Core\Event\GenericHookEvent), "hook_civicrm_postProcess", Object(Civi\Core\CiviEventDispatcher))
#6 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func((Array:2), Object(Civi\Core\Event\GenericHookEvent), "hook_civicrm_postProcess", Object(Civi\Core\CiviEventDispatcher))
#7 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch((Array:1), "hook_civicrm_postProcess", Object(Civi\Core\Event\GenericHookEvent))
#8 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/Civi/Core/CiviEventDispatcher.php(47): Symfony\Component\EventDispatcher\EventDispatcher->dispatch("hook_civicrm_postProcess", Object(Civi\Core\Event\GenericHookEvent))
#9 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(164): Civi\Core\CiviEventDispatcher->dispatch("hook_civicrm_postProcess", Object(Civi\Core\Event\GenericHookEvent))
#10 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(445): CRM_Utils_Hook->invoke((Array:2), "CRM_Contribute_Form_Contribution_Confirm", Object(CRM_Contribute_Form_Contribution_Confirm), NULL, NULL, NULL, NULL, "civicrm_postProcess")
#11 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Core/Form.php(516): CRM_Utils_Hook::postProcess("CRM_Contribute_Form_Contribution_Confirm", Object(CRM_Contribute_Form_Contribution_Confirm))
#12 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution/Confirm.php(1634): CRM_Core_Form->postProcessHook()
#13 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution/Confirm.php(1405): CRM_Contribute_Form_Contribution_Confirm->postProcessMembership((Array:59), "2", Object(CRM_Contribute_Form_Contribution_Confirm), (Array:46), (Array:0), (Array:0), (Array:13), (Array:1), TRUE, NULL, FALSE, "2", (Array:1), TRUE)
#14 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution/Confirm.php(2426): CRM_Contribute_Form_Contribution_Confirm->processMembership((Array:59), "2", (Array:0), (Array:0), (Array:46), (Array:1))
#15 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution/Confirm.php(2301): CRM_Contribute_Form_Contribution_Confirm->doMembershipProcessing("2", (Array:56), (Array:46), (Array:1))
#16 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution/Confirm.php(722): CRM_Contribute_Form_Contribution_Confirm->processFormSubmission("2")
#17 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Core/Form.php(489): CRM_Contribute_Form_Contribution_Confirm->postProcess()
#18 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Core/StateMachine.php(160): CRM_Core_Form->mainProcess()
#19 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Contribute_Form_Contribution_Confirm), "next", "Next")
#20 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Contribute_Form_Contribution_Confirm), "next")
#21 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Contribute_Form_Contribution_Confirm), "next")
#22 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("next")
#23 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(309): CRM_Core_Controller->run((Array:3), NULL)
#24 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:15))
#25 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#26 /home/thisdomain/domains/crm.thisdomain.org/public_html/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:3))
#27 [internal function](): civicrm_invoke("contribute", "transact")
#28 /home/thisdomain/domains/crm.thisdomain.org/public_html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#29 /home/thisdomain/domains/crm.thisdomain.org/public_html/index.php(21): menu_execute_active_handler()
#30 {main}

Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.
DB Error: no such field`

**Comment by tapashdatta** [comment]
Was unable to reproduce with CiviCRM 5.29.1, PHP 7.3.x, GDPR 2.9. Maybe specific environmental incompatibility issue. 
GDPR 2.7 is compatible with 5.0, 2.8 is compatible with 5.13, and 2.9 is compatible with 5.22. Please try one of this version.

**Comment by robbrandt** [comment]
Thanks.  Just tried 2.8, and the result is the same as with 2.7 and 2.9.  I don't believe this is related to php version.  We have two other instances of CiviCRM running in environments that we've tried to keep the same to avoid those types of issues, and both of those work fine.

Is there an easy way to determine WHICH field CiviCRM thinks is missing?

Thanks.

**Comment by tapashdatta** [comment]
There might be schema changes in GDPR related table when you have upgraded to recent version. You can try reverting changes to the table. Otherwise, if it works for other 2 sites but not for 3rd one, that points out that you may have issue  on 3rd site.

**Comment by robbrandt** [comment]
Hi.  I've made some progress debugging this.  The SQL that results in the error is:

SELECT codenum_13 FROM civicrm_value_sla_acceptance_4 WHERE entity_id = 10486 [nativecode=1054 ** Unknown column 'codenum_13' in 'field list']

codenum, I believe, is a custom field.  But I don't understand why CiviCRM and the GDPR module think that is should be in the SLA Acceptance table.

Any idea?

**Comment by robbrandt** [comment]
I now have a clue.  It seems there's some interference going on with another custom module we have running.
