### ISSUE TITLE
warnings from cronjob with php 7.4

### ISSUE THREAD

**Issue by mickkahn** [veda-consulting-company/uk.co.vedaconsulting.gdpr#287]
Since upgrading to php 7.4 I am getting an annoying warning message when cron jobs run:

Deprecated: Array and string offset access syntax with curly braces is deprecated in /home/customer/www/crm.coma.org/public_html/wp-content/uploads/civicrm/ext/uk.co.vedaconsulting.gdpr/gdpr.civix.php on line 246

A similar warning from another extension required an update to the file that looks quite substantial.

**Comment by homotechsual** [comment]
This should be fixed by a combination of #285 and #288 if/when these are reviewed/merged.
