### ISSUE TITLE
add a data export button

### ISSUE THREAD

**Issue by John-B** [veda-consulting-company/uk.co.vedaconsulting.gdpr#85]
Data subjects are entitled to receive the data we hold on them. A contact export does not include activity data, which must be generated seprately under Reports, as far as I can see. A button offering data export which includes all data (apart from fields we choose to exclude) and all activities for a data subject would be very useful. 

The data export would presumably be in CSV, and a PDF option woud be nice to have.

**Comment by veda-consulting** [comment]
@John-B our feeling is that the contact dashboard might better serve this? If it isn't fit for purpose then we might look to build something but its probably not something that will get used very often and therefore we'd need to get some collaboration to get it going.

**Comment by tapashdatta** [comment]
PR welcome. Thanks

**Comment by rsbroughton** [comment]
What sort of funding? (You can reply privately richard@rsbroughton.eu if you wish.)  Are there other users of this extension who might be interested in sharing costs?

**Comment by Sez0105** [comment]
Hello, is this something that is still being discussed? I can see the Funding required, is there an amount that is needed? 

Thanks
Sarah

**Comment by John-B** [comment]
As the prerson who opened the ticket I should respond. For the one Civi site I work on, the view is that no one has asked for a data export yet, and they may one day. Therefore we regard the feature as nice to have, and likely to be useful one day, though not a high priority.

**Comment by Sez0105** [comment]
Thanks John. The company I work for host over 60 clients, and I know a few (4-5) have had subject access requests, and have asked for help getting all the clients information out of Civi to send over. Most recent one last week. 
If it's something that needs funding I can raise this to the wider team, as I know this will keep coming up, and will be very helpful to clients going forward.
Thanks
Sarah

**Comment by tapashdatta** [comment]
Hi @John-B @Sez0105  Thanks for the heads up on this. Veda devs indicated it would require 1.5 days of effort to get it work. Please feel free to PM me for details.
